---
- hosts: localhost
  vars_files:
  - users.yml
  tasks:
  - name: create assignments directory
    file:
      path: "{{ submitted_dir }}"
      state: directory

  - name: create submitted directory
    file:
      path: "{{ submitted_dir }}/submitted"
      state: directory

  - name: create directories for each user
    file:
      path: "{{ submitted_dir }}/submitted/{{ item }}"
      state: directory
    with_items:
    - "{{ fetch_from }}"

  - name: remove existing files
    file:
      path: "{{ submitted_dir }}/submitted/{{ item[0] }}/{{ item[1] }}"
      state: absent
    with_nested:
    - "{{ fetch_from }}"
    - "{{ submitted_notebooks }}"

  - name: create directories for each prolem
    file:
      path: "{{ submitted_dir }}/submitted/{{ item[0] }}/{{ item[1] }}"
      state: directory
    with_nested:
    - "{{ fetch_from }}"
    - "{{ submitted_notebooks }}"

- hosts: nfs_server
  vars_files:
  - users.yml
  tasks:
  - set_fact: fetch_from="{{ fetch_from }}"

  - name: fetch assignments
    fetch:
      src: "/mnt/volume/home/{{ item[0] }}/assignments/Week{{ submitted_week }}/{{ item[1] }}.ipynb"
      dest: "{{ submitted_dir }}/submitted/{{ item[0] }}/{{ item[1] }}/{{ item[1] }}.ipynb"
      flat: yes
    with_nested:
    - "{{ fetch_from }}"
    - "{{ submitted_notebooks }}"
