---
- hosts: localhost
  vars_files:
  - users.yml
  tasks:
  - name: tar notebooks
    shell: tar -zcvf "{{ review_tar_dir }}/week{{ review_week }}_{{ item }}.tar.gz" \
        -C "{{ review_store_dir }}/Week{{ review_week }}/{{ item }}" .
    with_items: "{{ release_review_to }}"

- hosts:
  - nfs_server
  vars_files:
  - users.yml
  tasks:
  - name: create .info490 directory
    file:
      path: /mnt/volume/home/{{ item }}/.info490
      state: directory
      owner: 1000
      group: 1000
      recurse: yes
    with_items: "{{ release_review_to }}"

  - name: create rubric directory
    file:
      path: /mnt/volume/home/{{ item }}/.info490/rubric
      state: directory
      owner: 1000
      group: 1000
      recurse: yes
    with_items: "{{ release_review_to }}"

  - name: create rubric directory
    file:
      path: /mnt/volume/home/{{ item }}/.info490/grades
      state: directory
      owner: 1000
      group: 1000
      recurse: yes
    with_items: "{{ release_review_to }}"

  - name: copy rubric.py
    copy:
      src: ./rubric/rubric.py
      dest: /mnt/volume/home/{{ item }}/.info490/rubric/rubric.py
      owner: 1000
      group: 1000
    with_items: "{{ release_review_to }}"

  - name: create peer assessments directory
    file:
      path: /mnt/volume/home/{{ item }}/peer_assessments
      state: directory
      owner: 1000
      group: 1000
      recurse: yes
    with_items: "{{ release_review_to }}"

  - name: delete existing grades
    file:
      path: /mnt/volume/home/{{ item }}/.info490/grades/Week{{ review_week }}.yml
      state: absent
    with_items: "{{ release_review_to }}"

  - name: delete existing directory
    file:
      path: /mnt/volume/home/{{ item }}/peer_assessments/Week{{ review_week }}
      state: absent
    with_items: "{{ release_review_to }}"

  - name: create current week
    file:
      path: /mnt/volume/home/{{ item }}/peer_assessments/Week{{ review_week }}
      state: directory
      owner: 1000
      group: 1000
      recurse: yes
    with_items: "{{ release_review_to }}"

  - name: unarchive notebooks
    unarchive:
      src: "{{ review_tar_dir }}/week{{ review_week }}_{{ item }}.tar.gz"
      dest: "/mnt/volume/home/{{ item }}/peer_assessments/Week{{ review_week }}"
      owner: 1000
      group: 1000
    with_items: "{{ release_review_to }}"

  - name: check permissions
    file:
      path: /mnt/volume/home/{{ item }}/peer_assessments/Week{{ review_week }}
      state: directory
      owner: 1000
      group: 1000
      recurse: yes
    with_items: "{{ release_review_to }}"
