---
- hosts: 127.0.0.1
  connection: local
  vars_files:
  - week2.yml
  vars:
  - assign_week: 2 ### change this
  tasks:
  - name: tar notebooks
    shell: tar -zcvf "../tmp/week{{ assign_week }}_{{ item }}.tar.gz" -C "../peer_assessments/Week{{ assign_week }}/{{ item }}" .
    with_items: "{{ users }}"

- hosts:
  - nfs_server
  vars_files:
  - week2.yml
  vars:
  - assign_week: 2 ### change this
  tasks:
  - name: create peer assessments directory
    file:
      path: /mnt/volume/home/{{ item }}/peer_assessments
      state: directory
      owner: 1000
      group: 1000
      recurse: yes
    with_items: "{{ users }}"

  - name: delete existing directory
    file:
      path: /mnt/volume/home/{{ item }}/peer_assessments/Week{{ assign_week }}
      state: absent
    with_items: "{{ users }}"

  - name: create current week
    file:
      path: /mnt/volume/home/{{ item }}/peer_assessments/Week{{ assign_week }}
      state: directory
      owner: 1000
      group: 1000
      recurse: yes
    with_items: "{{ users }}"

  - name: unarchive notebooks
    unarchive:
      src: "../tmp/week{{ assign_week }}_{{ item }}.tar.gz"
      dest: "/mnt/volume/home/{{ item }}/peer_assessments/Week{{ assign_week }}"
      owner: 1000
      group: 1000
    with_items: "{{ users }}"

  - name: check permissions
    file:
      path: /mnt/volume/home/{{ item }}/peer_assessments/Week{{ assign_week }}
      state: directory
      owner: 1000
      group: 1000
      recurse: yes
    with_items: "{{ users }}"
