---
- hosts: 127.0.0.1
  connection: local
  tasks:
  - name: update git repo
    git:
      repo: https://github.com/ui-datascience/info490-sp16
      dest: ../info490-sp16
      update: yes

  - name: create assignment
    shell: tar -zcvf ../tmp/assignments.tar.gz -C "../info490-sp16/Week{{ assign_week }}/assignments" .
    vars:
    - assign_week: 3 # change this

- hosts:
  - nfs_server
  vars_files:
  - users.yml
  vars:
  - assign_week: 3 # change this
  - assign_dir: ../info490-sp16
  tasks:
  - name: create assignments directory
    file:
      path: /mnt/volume/home/{{ item }}/assignments
      state: directory
      owner: 1000
      group: 1000
      recurse: yes
    with_items:
#    - "{{ jupyterhub_admins }}"
#    - "{{ jupyterhub_users }}"
    - "{{ jupyterhub_testers }}"

  - name: remove this week if exists
    file:
      path: /mnt/volume/home/{{ item }}/assignments/Week{{ assign_week }}
      state: absent
    with_items:
#    - "{{ jupyterhub_admins }}"
#    - "{{ jupyterhub_users }}"
    - "{{ jupyterhub_testers }}"

  - name: create this week
    file:
      path: /mnt/volume/home/{{ item }}/assignments/Week{{ assign_week }}
      state: directory
      owner: 1000
      group: 1000
      recurse: yes
    with_items:
#    - "{{ jupyterhub_admins }}"
#    - "{{ jupyterhub_users }}"
    - "{{ jupyterhub_testers }}"
  
  - name: unarchive assignments
    unarchive:
      src: ../tmp/assignments.tar.gz
      dest: /mnt/volume/home/{{ item }}/assignments/Week{{ assign_week }}
      owner: 1000
      group: 1000
    with_items:
#    - "{{ jupyterhub_admins }}"
#    - "{{ jupyterhub_users }}"
    - "{{ jupyterhub_testers }}"
