---
- hosts: localhost
  tasks:
  - name: update git repo
    git:
      repo: https://github.com/ui-datascience/info490-sp16
      dest: "{{git_repo_dir}}"
      update: yes

  - name: create assignment
    shell: tar -zcvf ../tmp/assignments.tar.gz -C "{{git_repo_dir}}/Week{{assign_week}}/assignments" .

- hosts:
  - nfs_server
  vars_files:
  - users.yml
  tasks:
  - name: create assignments directory
    file:
      path: /mnt/volume/home/{{ item }}/assignments
      state: directory
      owner: 1000
      group: 1000
      recurse: yes
    with_items:
    - "{{release_assignments_to}}"

  - name: backup home directories
    shell: tar -zcvf /mnt/volume/backup/backup.{{ansible_date_time.date}}.tar.gz -C "/mnt/volume" home

  - stat: path=/mnt/volume/home/{{release_assignments_to[0]}}/assignments/Week{{ assign_week }}
    register: assign_dir
  - fail: msg="Assignment exists"
    when: assign_dir.stat.exists is defined and assign_dir.stat.exists

  - stat: path=/mnt/volume/home/{{release_assignments_to[1]}}/assignments/Week{{ assign_week }}
    register: assign_dir
  - fail: msg="Assignment exists"
    when: assign_dir.stat.exists is defined and assign_dir.stat.exists

  - stat: path=/mnt/volume/home/{{release_assignments_to[2]}}/assignments/Week{{ assign_week }}
    register: assign_dir
  - fail: msg="Assignment exists"
    when: assign_dir.stat.exists is defined and assign_dir.stat.exists

  - name: create this week
    file:
      path: /mnt/volume/home/{{ item }}/assignments/Week{{ assign_week }}
      state: directory
      owner: 1000
      group: 1000
      recurse: yes
    with_items:
    - "{{release_assignments_to}}"
  
  - name: unarchive assignments
    unarchive:
      src: ../tmp/assignments.tar.gz
      dest: /mnt/volume/home/{{ item }}/assignments/Week{{ assign_week }}
      owner: 1000
      group: 1000
    with_items:
    - "{{release_assignments_to}}"
